#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=dialog_incontext
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:50:00
#SBATCH --mem=64000M
#SBATCH --output=dialog_incontext_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

source activate dl2_gpu

cd $HOME/fromage-2/

srun python -u dialog_in_context.py --num_tests 50 --num_prompts_per_test 5 --ret_img "True" --num_qa_per_dialog 5
