#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=gvqa_vis_augm
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:10:00
#SBATCH --mem=64000M
#SBATCH --output=gvqa_all_included_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

source activate dl2_gpu

cd $HOME/FROMAGe-Prompting-Strategies/

srun python -u gvqa_visual_augmentation.py 