#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=img-ret
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:25:00
#SBATCH --mem=64000M
#SBATCH --output=img_retr_augm_text_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

source activate dl2_gpu

cd $HOME/FROMAGe-Prompting-Strategies/

srun python -u flickr_text_augmentation.py