#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=image_retrieval_flickr_demo
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=00:10:00
#SBATCH --mem=64000M
#SBATCH --output=image_retrieval_flickr_demo_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

source activate dl2_gpu

cd $HOME/FROMAGe-Prompting-Strategies/

srun python -u image_retrieval_flickr_demo.py 