#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=vist_inference
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=01:00:00
#SBATCH --mem=64000M
#SBATCH --output=vist_inference_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

source activate dl2_gpu

cd $HOME/fromage/

srun python -u vist_inference.py --num_stories 2 --num_captions 5 --include_images
